---
global:
  scrape_interval:  3s
  scrape_timeout: 5s
prometheusSpec:
  overrideHonorLabels: true
server:
  podAnnotations:
    "consul.hashicorp.com/connect-inject": "false"
  readinessProbeInitialDelay: 0
  securityContext:
    runAsUser: 65534
    runAsNonRoot: true
    runAsGroup: 655
  persistentVolume:
    enabled: false
  nodeSelector: 
    nodegroup: default
alertmanager:
  enabled: false
  nodeSelector: 
    nodegroup: default
nodeExporter:
  podAnnotations:
    "consul.hashicorp.com/connect-inject": "false"
pushgateway:
  podAnnotations:
    "consul.hashicorp.com/connect-inject": "false"
  nodeSelector: 
    nodegroup: default
kube-state-metrics:
  podAnnotations:
    "consul.hashicorp.com/connect-inject": "false"
  nodeSelector: 
    nodegroup: default
serviceAccounts:
  alertmanager:
    create: true
    name:
    annotations: {}
  nodeExporter:
    create: true
    name:
    annotations: {}
  pushgateway:
    create: true
    name:
    annotations: {}
  server:
    create: true
    name:
    annotations: {}
